# Houston Theme for Superfile
# Theme based on Houston syntax rules.

code_syntax_highlight = "monokai"

# ========= Border =========
file_panel_border = "#858b98"
footer_border = "#858b98"
sidebar_border = "#858b98"

# ========= Border Active =========
file_panel_border_active = "#00daef"
footer_border_active = "#4bf3c8"
modal_border_active = "#00daef"
sidebar_border_active = "#dc3657"

# ========= Background (bg) =========
file_panel_bg = "#17191e"
footer_bg = "#17191e"
full_screen_bg = "#17191e"
modal_bg = "#17191e"
sidebar_bg = "#17191e"

# ========= Foreground (fg) =========
file_panel_fg = "#eef0f9"
footer_fg = "#eef0f9"
full_screen_fg = "#eef0f9"
modal_fg = "#eef0f9"
sidebar_fg = "#eef0f9"

# ========= Special Color =========
cancel = "#ffd493"
correct = "#4bf3c8"
cursor = "#00daef"
error = "#dc3657"
hint = "#54b9ff"
gradient_color = ["#54b9ff", "#acafff"]

# ========= File Panel Special Items =========
file_panel_item_selected_bg = "#23262d"
file_panel_item_selected_fg = "#00daef"
file_panel_top_directory_icon = "#ffd493"
file_panel_top_path = "#ffd493"

# ========= Sidebar Special Items =========
sidebar_divider = "#858b98"
sidebar_item_selected_bg = "#17191e"
sidebar_item_selected_fg = "#00daef"
sidebar_title = "#00daef"

# ========= Modal Special Items =========
modal_cancel_bg = "#dc3657"
modal_cancel_fg = "#eef0f9"

modal_confirm_bg = "#00daef"
modal_confirm_fg = "#eef0f9"

# ========= Help Menu =========
help_menu_hotkey = "#00daef"
help_menu_title = "#acafff"
