# Retrokai Theme for Superfile
# Theme based on Monokai syntax rules.

# Code syntax highlight theme
code_syntax_highlight = "monokai"

# ========= Border =========
# Use RK_FG_DIM para bordas inativas/separadores
file_panel_border = "#7C7882"
footer_border = "#7C7882"
sidebar_border = "#7C7882"

# ========= Border Active =========
# Destaque com RK_CYAN, RK_GREEN e RK_RED
file_panel_border_active = "#66FFCC" # RK_CYAN
footer_border_active = "#A9DC76" # RK_GREEN
modal_border_active = "#66FFCC" # RK_CYAN
sidebar_border_active = "#FF6699" # RK_RED

# ========= Background (bg) =========
# Use RK_BG_MAIN para a maioria dos fundos
file_panel_bg = "#242226"
footer_bg = "#242226"
full_screen_bg = "#242226"
modal_bg = "#242226"
sidebar_bg = "#242226"

# ========= Foreground (fg) =========
# Use RK_FG_MAIN para a maioria dos textos
file_panel_fg = "#F8F5F2"
footer_fg = "#F8F5F2"
full_screen_fg = "#F8F5F2"
modal_fg = "#F8F5F2"
sidebar_fg = "#F8F5F2"

# ========= Special Color =========
# Cancelamento/aviso (RK_ORANGE/YELLOW)
cancel = "#FF9966"
# Cor de correção/sucesso (RK_GREEN)
correct = "#A9DC76"
# Cursor (RK_CYAN)
cursor = "#66FFCC"
# Erro (RK_RED)
error = "#FF6699"
# Hint/Sugestão (RK_BLUE)
hint = "#78DCE8"
# Gradient color can only have two color! (RK_BLUE e RK_PURPLE)
gradient_color = ["#78DCE8", "#B388FF"]

# ========= File Panel Special Items =========
# Fundo selecionado (RK_BG_LIGHT ou RK_BG_SELECT)
file_panel_item_selected_bg = "#2D2B30"
# Cor do texto selecionado (RK_CYAN)
file_panel_item_selected_fg = "#66FFCC"
# Ícone de diretório (RK_ORANGE)
file_panel_top_directory_icon = "#FF9966"
# Caminho (RK_ORANGE)
file_panel_top_path = "#FF9966"

# ========= Sidebar Special Items =========
# Divisor (RK_FG_DIM)
sidebar_divider = "#7C7882"
# Fundo selecionado na sidebar (manter o mesmo BG)
sidebar_item_selected_bg = "#242226"
# Texto selecionado na sidebar (RK_CYAN)
sidebar_item_selected_fg = "#66FFCC"
# Título da sidebar (RK_CYAN)
sidebar_title = "#66FFCC"

# ========= Modal Special Items =========
# Botão de Cancelar (Fundo: RK_RED, Texto: RK_FG_MAIN)
modal_cancel_bg = "#FF6699"
modal_cancel_fg = "#F8F5F2"

# Botão de Confirmar (Fundo: RK_CYAN, Texto: RK_FG_MAIN)
modal_confirm_bg = "#66FFCC"
modal_confirm_fg = "#F8F5F2"

# ========= Help Menu =========
# Hotkey (RK_CYAN)
help_menu_hotkey = "#66FFCC"
# Título (RK_PURPLE)
help_menu_title = "#B388FF"
